name: Build and push Docker image

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  REGISTRY: tools.playground.france-identite.gouv.fr

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build nginx image
        run: |
          docker build --target nginx \
            -t ${{ env.REGISTRY }}/dewa/verifier-demo-nginx:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/dewa/verifier-demo-nginx:latest \
            .

      - name: Build static image
        run: |
          docker build --target static \
            -t ${{ env.REGISTRY }}/dewa/verifier-demo:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/dewa/verifier-demo:latest \
            .

      - name: Push static image
        run: docker push --all-tags ${{ env.REGISTRY }}/dewa/verifier-demo

      - name: Push nginx image
        run: docker push --all-tags ${{ env.REGISTRY }}/dewa/verifier-demo-nginx
